const citys = [
        "Alipurduar, Alipurduar",
        "Falakata, Alipurduar",
        "Jaygaon, Alipurduar",
        "Madarihat, Alipurduar",
        "Kalchini, Alipurduar",
        "Birpara, Alipurduar",
        "Hamiltonganj, Alipurduar",
        "Hasimara, Alipurduar",
        "Rajabhatkhawa, Alipurduar",
        "Buxa, Alipurduar",
        "Salkumarhat, Alipurduar",
        "Kamakhyaguri, Alipurduar",
        "Jaigaon, Alipurduar",
        "Totopara, Alipurduar",
        "Dalgaon, Alipurduar",
        "Lankapara, Alipurduar",
        "Chuapara, Alipurduar",
        "Dalsingpara, Alipurduar",
        "Ballalguri, Alipurduar",
        "Kalipur, Alipurduar",
        "Kumargram, Alipurduar",
        "Barobisha, Alipurduar",
        "Shishujhumra, Alipurduar",
        "Patkapara, Alipurduar",
        "Dhanirampur, Alipurduar",
        "Sobhaganj, Alipurduar",
        "Parokata, Alipurduar",
        "Turturi, Alipurduar",
        "Mahakalguri, Alipurduar",
        "Mujnai, Alipurduar",
        "Garopara, Alipurduar",
        "Makrapara, Alipurduar",
        "Paschim Jitpur, Alipurduar",
        "Tapsikhata, Alipurduar",
        "Samuktala, Alipurduar",
        "Dakshin Rampur, Alipurduar",
        "Uttar Kalikhola, Alipurduar",
        "Marakhata, Alipurduar",
        "Dakshin Bharnobari, Alipurduar",
        "Kalabari, Alipurduar",
        "Bhutnirhat, Alipurduar",
        "Hatipota, Alipurduar",
        "Dhupguri, Alipurduar",
        "Malangi, Alipurduar",
        "Binnaguri, Alipurduar",
        "Chilapata, Alipurduar",
        "Kodalkati, Alipurduar",
        "Jateswar, Alipurduar",
        "Chowpathi, Alipurduar",
        "Khayerbari, Alipurduar",
        "Totgaon, Alipurduar",
        "Khairbari, Alipurduar",
        "Raimatang, Alipurduar",
        "Kalipukhuri, Alipurduar",
        "Chirakhawa, Alipurduar",
        "Bhatibari, Alipurduar",
        "Sishujhumra, Alipurduar",
        "Ramjhora, Alipurduar",
        "Bagribari, Alipurduar",
        "Gosairhat, Alipurduar",
        "Dima, Alipurduar",
        "Dalgaon Tea Garden, Alipurduar",
        "Chengmari, Alipurduar",
        "Chakchaka, Alipurduar",
        "Bindipara, Alipurduar",
        "Bandapani, Alipurduar",
        "Barobisha Bazaar, Alipurduar",
        "Chunabhati, Alipurduar",
        "Kharija Kakripara, Alipurduar",
        "Palashbari, Alipurduar",
        "Mechpara, Alipurduar",
        "Subhashini Tea Garden, Alipurduar",
        "Kashipur, Alipurduar",
        "Totopara Tading, Alipurduar",
        "Chhipra, Alipurduar",
        "Balapara, Alipurduar",
        "Uttar Mujnai, Alipurduar",
        "Dakshin Totgaon, Alipurduar",
        "Khagrabari, Alipurduar",
        "Paschim Kamakhyaguri, Alipurduar",
        "Uttar Haldibari, Alipurduar",
        "Dakshin Haldibari, Alipurduar",
        "Jalash Nadi, Alipurduar",
        "Singimari, Alipurduar",
        "Rangamati, Alipurduar",
        "Purba Shalbari, Alipurduar",
        "Paschim Shalbari, Alipurduar",
        "Hatsingimari, Alipurduar",
        "Baganpara, Alipurduar",
        "Subhasini, Alipurduar",
        "Parbatipur, Alipurduar",
        "Jaldapara, Alipurduar",
        "Bankura, Bankura",
    "Bishnupur, Bankura",
    "Sonamukhi, Bankura",
    "Khatra, Bankura",
    "Indpur, Bankura",
    "Onda, Bankura",
    "Patrasayer, Bankura",
    "Chhatna, Bankura",
    "Raipur, Bankura",
    "Simlapal, Bankura",
    "Taldangra, Bankura",
    "Joypur, Bankura",
    "Kotulpur, Bankura",
    "Barjora, Bankura",
    "Sarenga, Bankura",
    "Gangajalghati, Bankura",
    "Hirbandh, Bankura",
    "Radhanagar, Bankura",
    "Beliatore, Bankura",
    "Amarkanan, Bankura",
    "Shalibazar, Bankura",
    "Bikna, Bankura",
    "Kustore, Bankura",
    "Harmasra, Bankura",
    "Rangamati, Bankura",
    "Saltora, Bankura",
    "Gobindapur, Bankura",
    "Belut, Bankura",
    "Moukhira, Bankura",
    "Uttarbar, Bankura",
    "Kanchanpur, Bankura",
    "Kalapathar, Bankura",
    "Balsi, Bankura",
    "Durlavpur, Bankura",
    "Hatagram, Bankura",
    "Rasikganj, Bankura",
    "Kalipur, Bankura",
    "Palashdanga, Bankura",
    "Jorda, Bankura",
    "Chandai, Bankura",
    "Parulia, Bankura",
    "Bhaktabandh, Bankura",
    "Garhbeta, Bankura",
    "Narrah, Bankura",
    "Jagannathpur, Bankura",
    "Mankanali, Bankura",
    "Kangsabati, Bankura",
    "Beliara, Bankura",
    "Bagjola, Bankura",
    "Dhaban, Bankura",
    "Shyamsundarpur, Bankura",
    "Tiluri, Bankura",
    "Bhedua, Bankura",
    "Makra, Bankura",
    "Ranibandh, Bankura",
    "Chhendapathar, Bankura",
    "Tantipara, Bankura",
    "Kalyanpur, Bankura",
    "Birsingha, Bankura",
    "Ghosergram, Bankura",
    "Hatirampur, Bankura",
    "Jagatgram, Bankura",
    "Birsinghpur, Bankura",
    "Bagdiha, Bankura",
    "Chakaltore, Bankura",
    "Jhargram, Bankura",
    "Deuli, Bankura",
    "Rajpur, Bankura",
    "Lalgarh, Bankura",
    "Purandarpur, Bankura",
    "Chhatinasol, Bankura",
    "Beliashol, Bankura",
    "Kharar, Bankura",
    "Rupaspur, Bankura",
    "Bamunara, Bankura",
    "Beliatore Bazaar, Bankura",
    "Kansaripara, Bankura",
    "Chhandar, Bankura",
    "Pathardihi, Bankura",
    "Rajagram, Bankura",
    "Gopinathpur, Bankura",
    "Churamonipur, Bankura",
    "Jangalmahal, Bankura",
    "Gosaindanga, Bankura",
    "Jamda, Bankura",
    "Hirapur, Bankura",
    "Baskopa, Bankura",
    "Satnala, Bankura",
    "Baghata, Bankura",
    "Dignagar, Bankura",
    "Manbazar, Bankura",
    "Panuhat, Bankura",
    "Banasuria, Bankura",
    "Mougram, Bankura",
    "Ramchandrapur, Bankura",
    "Krishnapur, Bankura",
    "Suri, Birbhum",
    "Bolpur, Birbhum",
    "Rampurhat, Birbhum",
    "Nalhati, Birbhum",
    "Dubrajpur, Birbhum",
    "Illambazar, Birbhum",
    "Labpur, Birbhum",
    "Mayureswar, Birbhum",
    "Murarai, Birbhum",
    "Nanoor, Birbhum",
    "Sainthia, Birbhum",
    "Rajnagar, Birbhum",
    "Hetampur, Birbhum",
    "Khayrasole, Birbhum",
    "Kankalitala, Birbhum",
    "Chandidas Nanur, Birbhum",
    "Amarpur, Birbhum",
    "Bhabanipur, Birbhum",
    "Bakreswar, Birbhum",
    "Patharchapuri, Birbhum",
    "Hirapur, Birbhum",
    "Bhedia, Birbhum",
    "Khodarampur, Birbhum",
    "Chinpai, Birbhum",
    "Surul, Birbhum",
    "Gopalnagar, Birbhum",
    "Purandarpur, Birbhum",
    "Kasba, Birbhum",
    "Kamarpara, Birbhum",
    "Mallarpur, Birbhum",
    "Rajnagar Bazaar, Birbhum",
    "Sriniketan, Birbhum",
    "Santiniketan, Birbhum",
    "Chhatimtala, Birbhum",
    "Bhalki, Birbhum",
    "Bandhnala, Birbhum",
    "Kusumba, Birbhum",
    "Jashpur, Birbhum",
    "Kotasur, Birbhum",
    "Daronda, Birbhum",
    "Diknagar, Birbhum",
    "Panrui, Birbhum",
    "Charicha, Birbhum",
    "Haripur, Birbhum",
    "Nabasan, Birbhum",
    "Hatrasulganj, Birbhum",
    "Mohammad Bazar, Birbhum",
    "Mollarpur, Birbhum",
    "Suriya, Birbhum",
    "Jamtara, Birbhum",
    "Ghoshpur, Birbhum",
    "Ahmadpur, Birbhum",
    "Beluti, Birbhum",
    "Kankutia, Birbhum",
    "Rajbandh, Birbhum",
    "Kashipur, Birbhum",
    "Rasulpur, Birbhum",
    "Itanda, Birbhum",
    "Ramnagar, Birbhum",
    "Tantipara, Birbhum",
    "Sarbadhinpur, Birbhum",
    "Ballavpur, Birbhum",
    "Paruldanga, Birbhum",
    "Ghughumari, Birbhum",
    "Mankundi, Birbhum",
    "Bhabanandapur, Birbhum",
    "Dakshinkhanda, Birbhum",
    "Rampur, Birbhum",
    "Rajhat, Birbhum",
    "Basapara, Birbhum",
    "Kaliganj, Birbhum",
    "Panchami, Birbhum",
    "Basudha, Birbhum",
    "Mahula, Birbhum",
    "Kanutia, Birbhum",
    "Bahadurpur, Birbhum",
    "Debagram, Birbhum",
    "Hatabari, Birbhum",
    "Muktai, Birbhum",
    "Bharati, Birbhum",
    "Baganpara, Birbhum",
    "Sitala, Birbhum",
    "Murulia, Birbhum",
    "Kharbona, Birbhum",
    "Patelnagar, Birbhum",
    "Damra, Birbhum",
    "Laghata, Birbhum",
    "Nagari, Birbhum",
    "Madhabpur, Birbhum",
    "Bishnupur, Birbhum",
    "Anandapur, Birbhum",
    "Hinglow, Birbhum",
    "Labhpur Bazaar, Birbhum",
    "Hatikra, Birbhum",
    "Tinpahar, Birbhum",
    "Chopra, Birbhum",
    "Nandigram, Birbhum",
    "Cooch Behar, Cooch Behar",
    "Dinhata, Cooch Behar",
    "Mathabhanga, Cooch Behar",
    "Tufanganj, Cooch Behar",
    "Mekliganj, Cooch Behar",
    "Alambazar, Cooch Behar",
    "Haldibari, Cooch Behar",
    "Sadar, Cooch Behar",
    "Kochupara, Cooch Behar",
    "Srinagar, Cooch Behar",
    "Patlakhawa, Cooch Behar",
    "Bhotmari, Cooch Behar",
    "Bengalipara, Cooch Behar",
    "Ranishwar, Cooch Behar",
    "Balarampur, Cooch Behar",
    "Kumargram, Cooch Behar",
    "Garibpur, Cooch Behar",
    "Chhoto Alambazar, Cooch Behar",
    "Chowdhuripara, Cooch Behar",
    "Baroguri, Cooch Behar",
    "Bhabki, Cooch Behar",
    "Madhusree, Cooch Behar",
    "Khagrabari, Cooch Behar",
    "Hatiadanga, Cooch Behar",
    "Mahisganj, Cooch Behar",
    "Biral, Cooch Behar",
    "Baronaga, Cooch Behar",
    "Lalbari, Cooch Behar",
    "Kamakhyaguri, Cooch Behar",
    "Durgapur, Cooch Behar",
    "Kalai, Cooch Behar",
    "Harirampur, Cooch Behar",
    "Sukantapara, Cooch Behar",
    "Shibnagar, Cooch Behar",
    "Baladangi, Cooch Behar",
    "Dakshin Harirampur, Cooch Behar",
    "Dulaguri, Cooch Behar",
    "Raipur, Cooch Behar",
    "Laxmipur, Cooch Behar",
    "Manikpur, Cooch Behar",
    "Nabakumar, Cooch Behar",
    "Jitpur, Cooch Behar",
    "Rajganj, Cooch Behar",
    "Ghoramara, Cooch Behar",
    "Nandakumar, Cooch Behar",
    "Uttar Raipur, Cooch Behar",
    "Bholadanga, Cooch Behar",
    "Baisakhri, Cooch Behar",
    "Jitpur West, Cooch Behar",
    "Mahisadanga, Cooch Behar",
    "Pachagarh, Cooch Behar",
    "Madhabdiha, Cooch Behar",
    "Pundibari, Cooch Behar",
    "Kaliachak, Cooch Behar",
    "Rajkumar, Cooch Behar",
    "Baroguri Bazaar, Cooch Behar",
    "Sajirhat, Cooch Behar",
    "Sonakhali, Cooch Behar",
    "Kamarpara, Cooch Behar",
    "Uttar Raiganj, Cooch Behar",
    "Shibpur, Cooch Behar",
    "Bharatpur, Cooch Behar",
    "Durgapara, Cooch Behar",
    "Pankhali, Cooch Behar",
    "Bajitpur, Cooch Behar",
    "Kochubari, Cooch Behar",
    "Bongaon, Cooch Behar",
    "Golakganj, Cooch Behar",
    "Madhyamgram, Cooch Behar",
    "Chirukuri, Cooch Behar",
    "Malani, Cooch Behar",
    "Pratapganj, Cooch Behar",
    "Dhaldanga, Cooch Behar",
    "Aloknagar, Cooch Behar",
    "Majherhat, Cooch Behar",
    "Barendrapara, Cooch Behar",
    "Rajgaon, Cooch Behar",
    "Barama, Cooch Behar",
    "Kamarpara, Cooch Behar",
    "Sashikanta, Cooch Behar",
    "Kansai, Cooch Behar",
    "Uttar Manikpur, Cooch Behar",
    "Bhaturia, Cooch Behar",
    "Dudhpatil, Cooch Behar",
    "Balarampur North, Cooch Behar",
    "Kalkhira, Cooch Behar",
    "Kumirdaha, Cooch Behar",
    "Rajdanga, Cooch Behar",
    "Gachpara, Cooch Behar",
    "Bamunbari, Cooch Behar",
    "Pragpur, Cooch Behar",
    "Kokramari, Cooch Behar",
    "Jharbari, Cooch Behar",
    "Amlajora, Cooch Behar",
    "Naluabari, Cooch Behar",
    "Patimara, Cooch Behar",
    "Haral, Cooch Behar",
    "Mathurapur, Cooch Behar",
    "Sasaldanga, Cooch Behar",
    "Bhagram, Cooch Behar",
    "Bhutkhuri, Cooch Behar",
    "Jadabpur, Cooch Behar",
    "Chakchaka, Cooch Behar",
    "Balurghat, Dakshin Dinajpur",
    "Gangarampur, Dakshin Dinajpur",
    "Buniadpur, Dakshin Dinajpur",
    "Kumargram, Dakshin Dinajpur",
    "Tapan, Dakshin Dinajpur",
    "Harirampur, Dakshin Dinajpur",
    "Kaliaganj, Dakshin Dinajpur",
    "Brahmanbaria, Dakshin Dinajpur",
    "Madhabkathi, Dakshin Dinajpur",
    "Jitpur, Dakshin Dinajpur",
    "Kusumgram, Dakshin Dinajpur",
    "Raiganj, Dakshin Dinajpur",
    "Gajol, Dakshin Dinajpur",
    "Chandipur, Dakshin Dinajpur",
    "Naihati, Dakshin Dinajpur",
    "Sagar, Dakshin Dinajpur",
    "Uttarayon, Dakshin Dinajpur",
    "Bishnupur, Dakshin Dinajpur",
    "Rajganj, Dakshin Dinajpur",
    "Bagdah, Dakshin Dinajpur",
    "Kolkata, Dakshin Dinajpur",
    "Harinagar, Dakshin Dinajpur",
    "Kanchanpur, Dakshin Dinajpur",
    "Dhupguri, Dakshin Dinajpur",
    "Shibnagar, Dakshin Dinajpur",
    "Kundpur, Dakshin Dinajpur",
    "Baropara, Dakshin Dinajpur",
    "Mollarpur, Dakshin Dinajpur",
    "Chandanpara, Dakshin Dinajpur",
    "Kachikata, Dakshin Dinajpur",
    "Pathargram, Dakshin Dinajpur",
    "Sonarpur, Dakshin Dinajpur",
    "Bhatpara, Dakshin Dinajpur",
    "Ranishwar, Dakshin Dinajpur",
    "Patikapara, Dakshin Dinajpur",
    "Kushmandi, Dakshin Dinajpur",
    "Belur, Dakshin Dinajpur",
    "Khanpur, Dakshin Dinajpur",
    "Durgapur, Dakshin Dinajpur",
    "Mochpur, Dakshin Dinajpur",
    "Manikpur, Dakshin Dinajpur",
    "Jangalpara, Dakshin Dinajpur",
    "Ramnagar, Dakshin Dinajpur",
    "Radhikapur, Dakshin Dinajpur",
    "Balarampur, Dakshin Dinajpur",
    "Bariyadanga, Dakshin Dinajpur",
    "Dakshin Rajgram, Dakshin Dinajpur",
    "Harigram, Dakshin Dinajpur",
    "Jorai, Dakshin Dinajpur",
    "Kahalu, Dakshin Dinajpur",
    "Bakhrahat, Dakshin Dinajpur",
    "Gokulnagar, Dakshin Dinajpur",
    "Kachra, Dakshin Dinajpur",
    "Sonari, Dakshin Dinajpur",
    "Patrapur, Dakshin Dinajpur",
    "Chandil, Dakshin Dinajpur",
    "Mahammadpur, Dakshin Dinajpur",
    "Moynagar, Dakshin Dinajpur",
    "Raghunathganj, Dakshin Dinajpur",
    "Kherai, Dakshin Dinajpur",
    "Phulbari, Dakshin Dinajpur",
    "Chinchura, Dakshin Dinajpur",
    "Madanpur, Dakshin Dinajpur",
    "Amdanga, Dakshin Dinajpur",
    "Muktinagar, Dakshin Dinajpur",
    "Sujanpara, Dakshin Dinajpur",
    "Parulia, Dakshin Dinajpur",
    "Raikura, Dakshin Dinajpur",
    "Radhanagar, Dakshin Dinajpur",
    "Sarandha, Dakshin Dinajpur",
    "Madhusree, Dakshin Dinajpur",
    "Ghasigram, Dakshin Dinajpur",
    "Dholarpara, Dakshin Dinajpur",
    "Purba Hat, Dakshin Dinajpur",
    "Purulia, Dakshin Dinajpur",
    "Shyamnagar, Dakshin Dinajpur",
    "Baluabari, Dakshin Dinajpur",
    "Pratappur, Dakshin Dinajpur",
    "Uttargram, Dakshin Dinajpur",
    "Ramchandrapur, Dakshin Dinajpur",
    "Fatikpur, Dakshin Dinajpur",
    "Chanditala, Dakshin Dinajpur",
    "Chandipur, Dakshin Dinajpur",
    "Nababari, Dakshin Dinajpur",
    "Kashipur, Dakshin Dinajpur",
    "Narayanpur, Dakshin Dinajpur",
    "Tegulapara, Dakshin Dinajpur",
    "Gopalpur, Dakshin Dinajpur",
    "Majherpara, Dakshin Dinajpur",
    "Karatowa, Dakshin Dinajpur",
    "Harishchandrapur, Dakshin Dinajpur",
    "Ghanasyampur, Dakshin Dinajpur",
    "Basantipur, Dakshin Dinajpur",
    "Dharmapur, Dakshin Dinajpur",
    "Manipur, Dakshin Dinajpur",
    "Rajnagar, Dakshin Dinajpur",
    "Birampur, Dakshin Dinajpur",
    "Mohammadpur, Dakshin Dinajpur",
    "Khatian, Dakshin Dinajpur",
    "Chaltora, Dakshin Dinajpur",
    "Sajirhat, Dakshin Dinajpur",
    "Nagarbera, Dakshin Dinajpur",
    "Mangalbari, Dakshin Dinajpur",
    "Chotodogra, Dakshin Dinajpur",
    "Bakhra, Dakshin Dinajpur",
    "Baghati, Dakshin Dinajpur",
    "Radhagram, Dakshin Dinajpur",
    "Chirchira, Dakshin Dinajpur",
    "Bairagirhat, Dakshin Dinajpur",
    "Kashimnagar, Dakshin Dinajpur",
    "Darjeeling, Darjeeling",
    "Siliguri, Darjeeling",
    "Kalimpong, Darjeeling",
    "Kurseong, Darjeeling",
    "Mirik, Darjeeling",
    "Jorebungalow, Darjeeling",
    "Rohini, Darjeeling",
    "Takdah, Darjeeling",
    "Mahanadi, Darjeeling",
    "Lava, Darjeeling",
    "Pedong, Darjeeling",
    "Ghoom, Darjeeling",
    "Sukhia, Darjeeling",
    "Kurseong Bazar, Darjeeling",
    "Rangmohan, Darjeeling",
    "Singtam, Darjeeling",
    "Junction, Darjeeling",
    "Phansidewa, Darjeeling",
    "Mahananda, Darjeeling",
    "Samsing, Darjeeling",
    "Mirik Bazar, Darjeeling",
    "Gairibas, Darjeeling",
    "Bijanbari, Darjeeling",
    "Tung, Darjeeling",
    "Rimbik, Darjeeling",
    "Siddheshwar, Darjeeling",
    "Peshok, Darjeeling",
    "Mahanadi, Darjeeling",
    "Dilaram, Darjeeling",
    "Mungpoo, Darjeeling",
    "Kalapathar, Darjeeling",
    "Chota Mungpoo, Darjeeling",
    "Rimbik, Darjeeling",
    "Runglee, Darjeeling",
    "Joregaon, Darjeeling",
    "Bhanu Bhakta, Darjeeling",
    "Chibbo, Darjeeling",
    "Mukti, Darjeeling",
    "Bajrangbari, Darjeeling",
    "Chota Singtam, Darjeeling",
    "Gumba, Darjeeling",
    "Mahatma Gandhi Road, Darjeeling",
    "Pankhabari, Darjeeling",
    "Rungli Rungliot, Darjeeling",
    "Tung Dung, Darjeeling",
    "Mishmi, Darjeeling",
    "Darjeeling District, Darjeeling",
    "Aritar, Darjeeling",
    "Kalapathar, Darjeeling",
    "Kalimpong Bazaar, Darjeeling",
    "Gorkha Bazar, Darjeeling",
    "Shiv Mandir, Darjeeling",
    "Nayabazar, Darjeeling",
    "Siliguri Junction, Darjeeling",
    "Lambash, Darjeeling",
    "Rathang, Darjeeling",
    "Mahakal, Darjeeling",
    "Pellong, Darjeeling",
    "Chintan, Darjeeling",
    "Bazar Hill, Darjeeling",
    "Kumai, Darjeeling",
    "Chowk Bazar, Darjeeling",
    "Bichu, Darjeeling",
    "Darjeeling Chowk, Darjeeling",
    "Rhenock, Darjeeling",
    "Hilley, Darjeeling",
    "Aluabari, Darjeeling",
    "Bhandara, Darjeeling",
    "Rathung, Darjeeling",
    "Laxmi Bazar, Darjeeling",
    "Saksang, Darjeeling",
    "Bijanbari Bazar, Darjeeling",
    "Alubari, Darjeeling",
    "Giddepahar, Darjeeling",
    "Chibbo, Darjeeling",
    "Kalupara, Darjeeling",
    "Mungpoo Bazar, Darjeeling",
    "Sakyo, Darjeeling",
    "Tirpa, Darjeeling",
    "Khoribari, Darjeeling",
    "Simana, Darjeeling",
    "Lankapara, Darjeeling",
    "Bhanu Bhakta Bazar, Darjeeling",
    "Rangmohan Bazar, Darjeeling",
    "Lali, Darjeeling",
    "Gherabari, Darjeeling",
    "Kasturi, Darjeeling",
    "Gombu, Darjeeling",
    "Siliguri Bazar, Darjeeling",
    "Barodara, Darjeeling",
    "Rungli, Darjeeling",
    "Maji Bazar, Darjeeling",
    "Himalayan Range, Darjeeling",
    "Bujok, Darjeeling",
    "Kamarbari, Darjeeling",
    "Pashupati, Darjeeling",
    "Aga, Darjeeling",
    "Lingsey, Darjeeling",
    "Simana Bazar, Darjeeling",
    "Singhchew, Darjeeling",
    "Pangche, Darjeeling",
    "Dheklapara, Darjeeling",
    "Jitpur, Darjeeling",
    "Rungbong, Darjeeling",
    "Murgabari, Darjeeling",
    "Pheshok, Darjeeling",
    "Panchakanya, Darjeeling",
    "Tungstung, Darjeeling",
    "Rungdung, Darjeeling",
    "Chandannagar, Hooghly",
    "Hooghly, Hooghly",
    "Serampore, Hooghly",
    "Bansberia, Hooghly",
    "Singur, Hooghly",
    "Dhaniakhali, Hooghly",
    "Haripal, Hooghly",
    "Khanakul, Hooghly",
    "Chanditala, Hooghly",
    "Shibpur, Hooghly",
    "Magra, Hooghly",
    "Tarakeswar, Hooghly",
    "Arambagh, Hooghly",
    "Panchla, Hooghly",
    "Bhadreswar, Hooghly",
    "Kola, Hooghly",
    "Balagarh, Hooghly",
    "Nalikul, Hooghly",
    "Goghat, Hooghly",
    "Pandua, Hooghly",
    "Mogra, Hooghly",
    "Uttarpara, Hooghly",
    "Balarampur, Hooghly",
    "Rishra, Hooghly",
    "Durgapur, Hooghly",
    "Chinsurah, Hooghly",
    "Bansberia, Hooghly",
    "Shibpur, Hooghly",
    "Srirampur, Hooghly",
    "Goaldanga, Hooghly",
    "Ghoshpara, Hooghly",
    "Beldanga, Hooghly",
    "Kantalia, Hooghly",
    "Chandannagar, Hooghly",
    "Baruipur, Hooghly",
    "Sreerampur, Hooghly",
    "Tardaha, Hooghly",
    "Chanditala, Hooghly",
    "Burdwan, Hooghly",
    "Ankaria, Hooghly",
    "Baranagar, Hooghly",
    "Dhanikhali, Hooghly",
    "Jangipara, Hooghly",
    "Palashbari, Hooghly",
    "Nimdaha, Hooghly",
    "Boroa, Hooghly",
    "Fulia, Hooghly",
    "Tungipara, Hooghly",
    "Dakshin Kola, Hooghly",
    "Bengal, Hooghly",
    "Shantipur, Hooghly",
    "Furfur, Hooghly",
    "Singur, Hooghly",
    "Hatiara, Hooghly",
    "Kalachara, Hooghly",
    "Haridhan, Hooghly",
    "Uttarpara, Hooghly",
    "Chinsurah, Hooghly",
    "Balurghat, Hooghly",
    "Raigachi, Hooghly",
    "Bagan, Hooghly",
    "Mogra, Hooghly",
    "Matiari, Hooghly",
    "Raigachhi, Hooghly",
    "Khaligram, Hooghly",
    "Chowgacha, Hooghly",
    "Nalikul, Hooghly",
    "Ramchandrapur, Hooghly",
    "Belpukur, Hooghly",
    "Kumirdaha, Hooghly",
    "Sreerampur, Hooghly",
    "Bardhaman, Hooghly",
    "Bagatui, Hooghly",
    "Sadarghat, Hooghly",
    "Dharmapur, Hooghly",
    "Burdwan, Hooghly",
    "Ghuridaha, Hooghly",
    "Shivnarayan, Hooghly",
    "Basanti, Hooghly",
    "Barojora, Hooghly",
    "Kundulia, Hooghly",
    "Nabagram, Hooghly",
    "Kamarpara, Hooghly",
    "Chandrapur, Hooghly",
    "Dugri, Hooghly",
    "Bardhan, Hooghly",
    "Raghunathganj, Hooghly",
    "Haradanga, Hooghly",
    "Balarampur, Hooghly",
    "Chandnagar, Hooghly",
    "Jangipara, Hooghly",
    "Bengal, Hooghly",
    "Rishra, Hooghly",
    "Singur, Hooghly",
    "Tungipara, Hooghly",
    "Sitaldaha, Hooghly",
    "Basuli, Hooghly",
    "Raghunathganj, Hooghly",
    "Khodla, Hooghly",
    "Howrah, Howrah",
    "Shibpur, Howrah",
    "Liluah, Howrah",
    "Dumurjala, Howrah",
    "Salkia, Howrah",
    "Uluberia, Howrah",
    "Andul, Howrah",
    "Bagnan, Howrah",
    "Dasnagar, Howrah",
    "Madhabdi, Howrah",
    "Panchla, Howrah",
    "Amta, Howrah",
    "Domjur, Howrah",
    "Kolar, Howrah",
    "Barisha, Howrah",
    "Kolar, Howrah",
    "Belur, Howrah",
    "Kolkata, Howrah",
    "Sibpur, Howrah",
    "Chandannagar, Howrah",
    "Bally, Howrah",
    "Singur, Howrah",
    "Sankrail, Howrah",
    "Maheshtala, Howrah",
    "Tarakeswar, Howrah",
    "Kolar, Howrah",
    "Bally, Howrah",
    "Shibpur, Howrah",
    "Balarampur, Howrah",
    "Nimdaha, Howrah",
    "Gorabari, Howrah",
    "Shyamnagar, Howrah",
    "Sialdaha, Howrah",
    "Bagnan, Howrah",
    "Bishnupur, Howrah",
    "Keshabganj, Howrah",
    "Raipur, Howrah",
    "Howrah, Howrah",
    "Chinsurah, Howrah",
    "Kamarpara, Howrah",
    "Chanditala, Howrah",
    "Shibpur, Howrah",
    "Uttarpara, Howrah",
    "Tungipara, Howrah",
    "Tarakeswar, Howrah",
    "Shivpur, Howrah",
    "Kalachara, Howrah",
    "Ganguly Bagan, Howrah",
    "Sreerampur, Howrah",
    "Kolar, Howrah",
    "Baldanga, Howrah",
    "Nabagram, Howrah",
    "Mahishrekha, Howrah",
    "Panchla, Howrah",
    "Kumirdaha, Howrah",
    "Dumurjala, Howrah",
    "Chandannagar, Howrah",
    "Amraipur, Howrah",
    "Howrah, Howrah",
    "Balarampur, Howrah",
    "Kamarpara, Howrah",
    "Panchla, Howrah",
    "Rishra, Howrah",
    "Chandnagar, Howrah",
    "Raghunathganj, Howrah",
    "Howrah, Howrah",
    "Bansberia, Howrah",
    "Mahishrekha, Howrah",
    "Salkia, Howrah",
    "Jangipara, Howrah",
    "Tungipara, Howrah",
    "Kolar, Howrah",
    "Uluberia, Howrah",
    "Alipurduar, Jalpaiguri",
    "Falakata, Jalpaiguri",
    "Jaygaon, Jalpaiguri",
    "Madarihat, Jalpaiguri",
    "Kalchini, Jalpaiguri",
    "Birpara, Jalpaiguri",
    "Hamiltonganj, Jalpaiguri",
    "Hasimara, Jalpaiguri",
    "Rajabhatkhawa, Jalpaiguri",
    "Buxa, Jalpaiguri",
    "Salkumarhat, Jalpaiguri",
    "Kamakhyaguri, Jalpaiguri",
    "Jaigaon, Jalpaiguri",
    "Totopara, Jalpaiguri",
    "Dalgaon, Jalpaiguri",
    "Lankapara, Jalpaiguri",
    "Chuapara, Jalpaiguri",
    "Dalsingpara, Jalpaiguri",
    "Ballalguri, Jalpaiguri",
    "Kalipur, Jalpaiguri",
    "Kumargram, Jalpaiguri",
    "Barobisha, Jalpaiguri",
    "Shishujhumra, Jalpaiguri",
    "Patkapara, Jalpaiguri",
    "Dhanirampur, Jalpaiguri",
    "Sobhaganj, Jalpaiguri",
    "Parokata, Jalpaiguri",
    "Turturi, Jalpaiguri",
    "Mahakalguri, Jalpaiguri",
    "Mujnai, Jalpaiguri",
    "Garopara, Jalpaiguri",
    "Makrapara, Jalpaiguri",
    "Paschim Jitpur, Jalpaiguri",
    "Tapsikhata, Jalpaiguri",
    "Samuktala, Jalpaiguri",
    "Dakshin Rampur, Jalpaiguri",
    "Uttar Kalikhola, Jalpaiguri",
    "Marakhata, Jalpaiguri",
    "Dakshin Bharnobari, Jalpaiguri",
    "Kalabari, Jalpaiguri",
    "Bhutnirhat, Jalpaiguri",
    "Hatipota, Jalpaiguri",
    "Dhupguri, Jalpaiguri",
    "Malangi, Jalpaiguri",
    "Binnaguri, Jalpaiguri",
    "Chilapata, Jalpaiguri",
    "Kodalkati, Jalpaiguri",
    "Jateswar, Jalpaiguri",
    "Chowpathi, Jalpaiguri",
    "Khayerbari, Jalpaiguri",
    "Totgaon, Jalpaiguri",
    "Khairbari, Jalpaiguri",
    "Raimatang, Jalpaiguri",
    "Kalipukhuri, Jalpaiguri",
    "Chirakhawa, Jalpaiguri",
    "Bhatibari, Jalpaiguri",
    "Sishujhumra, Jalpaiguri",
    "Ramjhora, Jalpaiguri",
    "Bagribari, Jalpaiguri",
    "Gosairhat, Jalpaiguri",
    "Dima, Jalpaiguri",
    "Dalgaon Tea Garden, Jalpaiguri",
    "Chengmari, Jalpaiguri",
    "Chakchaka, Jalpaiguri",
    "Bindipara, Jalpaiguri",
    "Bandapani, Jalpaiguri",
    "Barobisha Bazaar, Jalpaiguri",
    "Chunabhati, Jalpaiguri",
    "Kharija Kakripara, Jalpaiguri",
    "Palashbari, Jalpaiguri",
    "Mechpara, Jalpaiguri",
    "Subhashini Tea Garden, Jalpaiguri",
    "Kashipur, Jalpaiguri",
    "Totopara Tading, Jalpaiguri",
    "Chhipra, Jalpaiguri",
    "Balapara, Jalpaiguri",
    "Uttar Mujnai, Jalpaiguri",
    "Dakshin Totgaon, Jalpaiguri",
    "Khagrabari, Jalpaiguri",
    "Paschim Kamakhyaguri, Jalpaiguri",
    "Uttar Haldibari, Jalpaiguri",
    "Dakshin Haldibari, Jalpaiguri",
    "Jalash Nadi, Jalpaiguri",
    "Singimari, Jalpaiguri",
    "Rangamati, Jalpaiguri",
    "Purba Shalbari, Jalpaiguri",
    "Paschim Shalbari, Jalpaiguri",
    "Hatsingimari, Jalpaiguri",
    "Baganpara, Jalpaiguri",
    "Subhasini, Jalpaiguri",
    "Parbatipur, Jalpaiguri",
    "Jaldapara, Jalpaiguri",
    "Jhargram, Jhargram",
    "Belpahari, Jhargram",
    "Binpur, Jhargram",
    "Gopiballavpur, Jhargram",
    "Silda, Jhargram",
    "Jamboni, Jhargram",
    "Sankrail, Jhargram",
    "Gandhi, Jhargram",
    "Chandrakona, Jhargram",
    "Dantan, Jhargram",
    "Narayangarh, Jhargram",
    "Shibpur, Jhargram",
    "Manbazar, Jhargram",
    "Ranishwar, Jhargram",
    "Hindusthan, Jhargram",
    "Sankra, Jhargram",
    "Kanksa, Jhargram",
    "Keshpur, Jhargram",
    "Belgachhia, Jhargram",
    "Baitarani, Jhargram",
    "Laxminarayanpur, Jhargram",
    "Chandni, Jhargram",
    "Madhupur, Jhargram",
    "Patpur, Jhargram",
    "Birsinghpur, Jhargram",
    "Sundar, Jhargram",
    "Salboni, Jhargram",
    "Debra, Jhargram",
    "Barabazar, Jhargram",
    "Madhupur, Jhargram",
    "Ramjibanpur, Jhargram",
    "Gurudwara, Jhargram",
    "Haripada, Jhargram",
    "Madhusudankathi, Jhargram",
    "Amraipur, Jhargram",
    "Dhanghata, Jhargram",
    "Alampur, Jhargram",
    "Mukutmonipur, Jhargram",
    "Raipur, Jhargram",
    "Mogra, Jhargram",
    "Bankura, Jhargram",
    "Kalabagan, Jhargram",
    "Krishnanagar, Jhargram",
    "Mohammadpur, Jhargram",
    "Gujarat, Jhargram",
    "Ramnagar, Jhargram",
    "Amitpur, Jhargram",
    "Bajra, Jhargram",
    "Pondul, Jhargram",
    "Asrampur, Jhargram",
    "Ramkrishnapur, Jhargram",
    "Bhubaneshwar, Jhargram",
    "Mongram, Jhargram",
    "Hindustan, Jhargram",
    "Kolar, Jhargram",
    "Chunakhali, Jhargram",
    "Kenduli, Jhargram",
    "Burdwan, Jhargram",
    "Mogra, Jhargram",
    "Ranishwar, Jhargram",
    "Madhupur, Jhargram",
    "Daldali, Jhargram",
    "Barajora, Jhargram",
    "Sonamukhi, Jhargram",
    "Kolat, Jhargram",
    "Manikpara, Jhargram",
    "Pratappur, Jhargram",
    "Khasmohanpur, Jhargram",
    "Badas, Jhargram",
    "Patul, Jhargram",
    "Sarenga, Jhargram",
    "Guchhatra, Jhargram",
    "Kenduli, Jhargram",
    "Panchghora, Jhargram",
    "Salim, Jhargram",
    "Bhujia, Jhargram",
    "Banol, Jhargram",
    "Malhara, Jhargram",
    "Parulia, Jhargram",
    "Rakhari, Jhargram",
    "Indrabati, Jhargram",
    "Dumarbari, Jhargram",
    "Rajpur, Jhargram",
    "Gholgram, Jhargram",
    "Gadabari, Jhargram",
    "Daniara, Jhargram",
    "Hafizpur, Jhargram",
    "Pankrishnagar, Jhargram",
    "Chunakhali, Jhargram",
    "Dakshin Purulia, Jhargram",
    "Jojok, Jhargram",
     "Kalimpong, Kalimpong",
    "Lolegaon, Kalimpong",
    "Rishyap, Kalimpong",
    "Pashupati, Kalimpong",
    "Gorubathan, Kalimpong",
    "Pedong, Kalimpong",
    "Munsiari, Kalimpong",
    "Aritar, Kalimpong",
    "Delo, Kalimpong",
    "Sillery Gaon, Kalimpong",
    "Kalijhora, Kalimpong",
    "Lava, Kalimpong",
    "Charkhole, Kalimpong",
    "Sankosh, Kalimpong",
    "Kalimati, Kalimpong",
    "Nagri, Kalimpong",
    "Samthar, Kalimpong",
    "Ravangla, Kalimpong",
    "Bunkulung, Kalimpong",
    "Kurseong, Kalimpong",
    "Pachey, Kalimpong",
    "Kalimpong Hill, Kalimpong",
    "Chauphuli, Kalimpong",
    "Melli, Kalimpong",
    "Sukhia, Kalimpong",
    "Daling, Kalimpong",
    "Nambu, Kalimpong",
    "Takdah, Kalimpong",
    "Mangwa, Kalimpong",
    "Bhanu, Kalimpong",
    "Bhalukhop, Kalimpong",
    "Banjhakri, Kalimpong",
    "Sittong, Kalimpong",
    "Hilley, Kalimpong",
    "Chitre, Kalimpong",
    "Mongpu, Kalimpong",
    "Rangpo, Kalimpong",
    "Lalung, Kalimpong",
    "Chengmari, Kalimpong",
    "Melli Bazar, Kalimpong",
    "Teesta, Kalimpong",
    "Sevoke, Kalimpong",
    "Mungpoo, Kalimpong",
    "Dhap, Kalimpong",
    "Kalimpong Bazaar, Kalimpong",
    "Jiti, Kalimpong",
    "Bodhgaya, Kalimpong",
    "Sumbuk, Kalimpong",
    "Sengay, Kalimpong",
    "Vishal, Kalimpong",
    "Takda, Kalimpong",
    "Pacheybong, Kalimpong",
    "Shiliguri, Kalimpong",
    "Sonada, Kalimpong",
    "Lama, Kalimpong",
    "Bara Mangal, Kalimpong",
    "Teesta Bazaar, Kalimpong",
    "Jorethang, Kalimpong",
    "Malda, Malda",
    "English Bazar, Malda",
    "Bamangola, Malda",
    "Harishchandrapur, Malda",
    "Chanchal, Malda",
    "Kaliachak, Malda",
    "Gazole, Malda",
    "Mothabari, Malda",
    "Manikchak, Malda",
    "Shamsherganj, Malda",
    "Ratua, Malda",
    "Bhaluka, Malda",
    "Sutahata, Malda",
    "Maharajpur, Malda",
    "Sutrapara, Malda",
    "Sarikala, Malda",
    "Kundali, Malda",
    "Jalalpur, Malda",
    "Dhubulia, Malda",
    "Birsinghpur, Malda",
    "Gajol, Malda",
    "Chandipur, Malda",
    "Panditpara, Malda",
    "Mochipara, Malda",
    "Kola, Malda",
    "Baro, Malda",
    "Beldanga, Malda",
    "Kulkul, Malda",
    "Nimti, Malda",
    "Sundarpur, Malda",
    "Gokulnagar, Malda",
    "Bara Jhar, Malda",
    "Gujuli, Malda",
    "Lalgola, Malda",
    "Jadabpur, Malda",
    "Kalikapur, Malda",
    "Raghunathganj, Malda",
    "Khatian, Malda",
    "Madanpur, Malda",
    "Jitpur, Malda",
    "Dhulian, Malda",
    "Sukhani, Malda",
    "Chhatra, Malda",
    "Keshabganj, Malda",
    "Ramganj, Malda",
    "Suri, Malda",
    "Paruli, Malda",
    "Rajgram, Malda",
    "Khoyra, Malda",
    "Bagdah, Malda",
    "Uttarpara, Malda",
    "Kolkata Road, Malda",
    "Balurghat, Malda",
    "Jitpur, Malda",
    "Kashimbazar, Malda",
    "Patuli, Malda",
    "Sankarpara, Malda",
    "Shitalakuri, Malda",
    "Bidhannagar, Malda",
    "Alampur, Malda",
    "Nawapara, Malda",
    "Belpukur, Malda",
    "Rupganj, Malda",
    "Kamarpara, Malda",
    "Jora, Malda",
    "Hingalganj, Malda",
    "Sajra, Malda",
    "Bapujee, Malda",
    "Malda Town, Malda",
    "Madhubani, Malda",
    "Bhagwanpur, Malda",
    "Basanti, Malda",
    "Pachim Kalitola, Malda",
    "Falta, Malda",
    "Sadikpur, Malda",
    "Basudebpur, Malda",
    "Rajpur, Malda",
    "Tapan, Malda",
    "Ranishwar, Malda",
    "Patipukur, Malda",
    "Nayagram, Malda",
    "Gokulnagar, Malda",
    "Sundarban, Malda",
    "Nayagram, Malda",
    "Kalampur, Malda",
    "Baribhasa, Malda",
    "Goribpur, Malda",
    "Alapur, Malda",
    "Rajgram, Malda",
    "Patuli, Malda",
    "Murarai, Malda",
    "Gokulnagar, Malda",
    "Nayanagar, Malda",
    "Fakirganj, Malda",
    "Chandipur, Malda",
    "Uttorayon, Malda",
    "Satyapriya, Malda",
    "Murshidabad, Murshidabad",
    "Berhampore, Murshidabad",
    "Beldanga, Murshidabad",
    "Kandi, Murshidabad",
    "Domkal, Murshidabad",
    "Raghunathganj, Murshidabad",
    "Nabagram, Murshidabad",
    "Suti, Murshidabad",
    "Jangipur, Murshidabad",
    "Khargram, Murshidabad",
    "Sagardighi, Murshidabad",
    "Lalgola, Murshidabad",
    "Kamarpara, Murshidabad",
    "Murarai, Murshidabad",
    "Mansatala, Murshidabad",
    "Samsherganj, Murshidabad",
    "Kalikapur, Murshidabad",
    "Azimganj, Murshidabad",
    "Gora, Murshidabad",
    "Sadar, Murshidabad",
    "Farakka, Murshidabad",
    "Kansona, Murshidabad",
    "Nimasari, Murshidabad",
    "Ranishwar, Murshidabad",
    "Nimtita, Murshidabad",
    "Bhabnagar, Murshidabad",
    "Kola, Murshidabad",
    "Bamangola, Murshidabad",
    "Shibnagar, Murshidabad",
    "Dohazari, Murshidabad",
    "Islampur, Murshidabad",
    "Mathurapur, Murshidabad",
    "Purba Jitpur, Murshidabad",
    "Nandanpur, Murshidabad",
    "Sadar Bazar, Murshidabad",
    "Kotalpur, Murshidabad",
    "Rajgram, Murshidabad",
    "Alambazar, Murshidabad",
    "Bhasra, Murshidabad",
    "Chandpur, Murshidabad",
    "Raghunathganj Bazar, Murshidabad",
    "Shibpur, Murshidabad",
    "Chandipur, Murshidabad",
    "Uttarayan, Murshidabad",
    "Kolkata, Murshidabad",
    "Harirampur, Murshidabad",
    "Khairabari, Murshidabad",
    "Haripara, Murshidabad",
    "Rajganj, Murshidabad",
    "Balia, Murshidabad",
    "Narkeldanga, Murshidabad",
    "Ganganagar, Murshidabad",
    "Gohalbari, Murshidabad",
    "Jibanpur, Murshidabad",
    "Kachur, Murshidabad",
    "Ramchandrapur, Murshidabad",
    "Jitpur, Murshidabad",
    "Shitalganj, Murshidabad",
    "Amraipur, Murshidabad",
    "Tapan, Murshidabad",
    "Dhulian, Murshidabad",
    "Sonamukhi, Murshidabad",
    "Ramnagar, Murshidabad",
    "Kailashnagar, Murshidabad",
    "Sagarpara, Murshidabad",
    "Madhabganj, Murshidabad",
    "Jabdipur, Murshidabad",
    "Bhagar, Murshidabad",
    "Gharpara, Murshidabad",
    "Jorkhali, Murshidabad",
    "Kaliadaha, Murshidabad",
    "Phulbari, Murshidabad",
    "Barabagan, Murshidabad",
    "Srirampur, Murshidabad",
    "Ranishwar Bazar, Murshidabad",
    "Gomoh, Murshidabad",
    "Kaliganj, Murshidabad",
    "Rajapur, Murshidabad",
    "Bojai, Murshidabad",
    "Kamarpur, Murshidabad",
    "Bhiringi, Murshidabad",
    "Panchanantala, Murshidabad",
    "Shyamganj, Murshidabad",
    "Jhaudi, Murshidabad",
    "Shibdhan, Murshidabad",
    "Sonai, Murshidabad",
    "Kundal, Murshidabad",
    "Parsanapur, Murshidabad",
    "Bairagi, Murshidabad",
    "Banshkhali, Murshidabad",
    "Balarampur, Murshidabad",
    "Baisnabnagar, Murshidabad",
    "Dakshin Rajgram, Murshidabad",
    "Mohammadpur, Murshidabad",
    "Gopinathganj, Murshidabad",
    "Bangalipara, Murshidabad",
    "Phuljori, Murshidabad",
    "Balurghat, Murshidabad",
    "Manikpara, Murshidabad",
    "Dugmara, Murshidabad",
    "Harinagar, Murshidabad",
    "Chanchal, Murshidabad",
    "Krishnanagar, Murshidabad",
    "Bohirgram, Murshidabad",
    "Bairagipara, Murshidabad",
    "Chanditala, Murshidabad",
    "Suti Bazar, Murshidabad",
    "Amdanga, Murshidabad",
    "Mathurapur Bazar, Murshidabad",
    "Sundarpur, Murshidabad",
    "Nadia, Nadia",
    "Krishnanagar, Nadia",
    "Kalyani, Nadia",
    "Ranaghat, Nadia",
    "Chakdaha, Nadia",
    "Nabadwip, Nadia",
    "Karimpur, Nadia",
    "Tehatta, Nadia",
    "Madhabganj, Nadia",
    "Santipur, Nadia",
    "Nakashipara, Nadia",
    "Bethuadahari, Nadia",
    "Jirat, Nadia",
    "Krishnanagar Court, Nadia",
    "Brahmanpara, Nadia",
    "Durgapur, Nadia",
    "Jemari, Nadia",
    "Bagdah, Nadia",
    "Dakshin Durgapur, Nadia",
    "Murarai, Nadia",
    "Gajol, Nadia",
    "Raghunathganj, Nadia",
    "Nabadwip Kachhari, Nadia",
    "Banshberia, Nadia",
    "Majhergram, Nadia",
    "Bhandarkuri, Nadia",
    "Purandarpur, Nadia",
    "Kolkata, Nadia",
    "Aminpur, Nadia",
    "Sonarpur, Nadia",
    "Kanchrapara, Nadia",
    "Bongram, Nadia",
    "Srirampur, Nadia",
    "Chandpara, Nadia",
    "Dhatrigram, Nadia",
    "Sadpur, Nadia",
    "Bamunari, Nadia",
    "Alampur, Nadia",
    "Mahammadpur, Nadia",
    "Narayanpur, Nadia",
    "Tulsipur, Nadia",
    "Brahmapur, Nadia",
    "Kaliaganj, Nadia",
    "Shibpur, Nadia",
    "Mogra, Nadia",
    "Nadgram, Nadia",
    "Bholar, Nadia",
    "Panchmura, Nadia",
    "Matla, Nadia",
    "Jitpur, Nadia",
    "Amjora, Nadia",
    "Banshi, Nadia",
    "Narayanpur, Nadia",
    "Haringhata, Nadia",
    "Satyen Bagan, Nadia",
    "Tamluk, Nadia",
    "Basudebpur, Nadia",
    "Gobindapur, Nadia",
    "Kamakhyaguri, Nadia",
    "Jambad, Nadia",
    "Chhatrakhali, Nadia",
    "Murarai, Nadia",
    "Naihatta, Nadia",
    "Sondaha, Nadia",
    "Tulsihatta, Nadia",
    "Lalgola, Nadia",
    "Kachari, Nadia",
    "Gouripur, Nadia",
    "Gopalnagar, Nadia",
    "Sailapur, Nadia",
    "Bashkhali, Nadia",
    "Chhatna, Nadia",
    "Jagatdal, Nadia",
    "Jayanagar, Nadia",
    "Raghunathganj, Nadia",
    "Gora Bazar, Nadia",
    "Uttarpara, Nadia",
    "Majhergram, Nadia",
    "Dugui, Nadia",
    "Nityanandapur, Nadia",
    "Chandpara, Nadia",
    "Shibpur, Nadia",
    "Manirampur, Nadia",
    "Sonarpur, Nadia",
    "Salkumarhat, Nadia",
    "Barasat, North 24 Parganas",
    "Barrackpore, North 24 Parganas",
    "Habra, North 24 Parganas",
    "Dum Dum, North 24 Parganas",
    "Ashoknagar, North 24 Parganas",
    "Naihati, North 24 Parganas",
    "Bongaon, North 24 Parganas",
    "Kamarhati, North 24 Parganas",
    "Titagarh, North 24 Parganas",
    "Kharda, North 24 Parganas",
    "Sandeshkhali, North 24 Parganas",
    "Rajpur Sonarpur, North 24 Parganas",
    "Nandankanan, North 24 Parganas",
    "North Dumdum, North 24 Parganas",
    "Baranagar, North 24 Parganas",
    "Sodepur, North 24 Parganas",
    "New Barrackpore, North 24 Parganas",
    "Panchla, North 24 Parganas",
    "Kolar, North 24 Parganas",
    "Canning, North 24 Parganas",
    "Sujanpur, North 24 Parganas",
    "Bagda, North 24 Parganas",
    "Basirhat, North 24 Parganas",
    "Rajendrapur, North 24 Parganas",
    "Berachampa, North 24 Parganas",
    "Nalikul, North 24 Parganas",
    "Haroa, North 24 Parganas",
    "Rajarhat, North 24 Parganas",
    "Nimta, North 24 Parganas",
    "Bansberia, North 24 Parganas",
    "Falta, North 24 Parganas",
    "Baruipur, North 24 Parganas",
    "Sagar, North 24 Parganas",
    "Garia, North 24 Parganas",
    "Brahmapur, North 24 Parganas",
    "Nayabad, North 24 Parganas",
    "Dakshin Barasat, North 24 Parganas",
    "Uttarpara, North 24 Parganas",
    "Dholai, North 24 Parganas",
    "Jorashanko, North 24 Parganas",
    "Haridevpur, North 24 Parganas",
    "Sukchar, North 24 Parganas",
    "Basudebpur, North 24 Parganas",
    "Siliguri, North 24 Parganas",
    "Shyampur, North 24 Parganas",
    "Tikiapara, North 24 Parganas",
    "Kaliaganj, North 24 Parganas",
    "Chandpara, North 24 Parganas",
    "Panchra, North 24 Parganas",
    "Sarat Bose Road, North 24 Parganas",
    "Raghunathganj, North 24 Parganas",
    "Mahammadpur, North 24 Parganas",
    "Jagaddal, North 24 Parganas",
    "Fakirganj, North 24 Parganas",
    "Kaliapara, North 24 Parganas",
    "Sukharia, North 24 Parganas",
    "Khudirampur, North 24 Parganas",
    "Kanchrapara, North 24 Parganas",
    "Bengaluru, North 24 Parganas",
    "Srinagar, North 24 Parganas",
    "Balurghat, North 24 Parganas",
    "Jotshree, North 24 Parganas",
    "Shibpur, North 24 Parganas",
    "Sadhurpara, North 24 Parganas",
    "Sonarpur, North 24 Parganas",
    "Jalebighat, North 24 Parganas",
    "Banamalipur, North 24 Parganas",
    "Sukhna, North 24 Parganas",
    "Pailan, North 24 Parganas",
    "Sealdah, North 24 Parganas",
    "Khadinapara, North 24 Parganas",
    "Kashipur, North 24 Parganas",
    "Bally, North 24 Parganas",
    "Egra, North 24 Parganas",
    "Titas, North 24 Parganas",
    "Kamarkundu, North 24 Parganas",
    "Asansol, Paschim Bardhaman",
    "Raniganj, Paschim Bardhaman",
    "Durgapur, Paschim Bardhaman",
    "Kulti, Paschim Bardhaman",
    "Jamuria, Paschim Bardhaman",
    "Barabani, Paschim Bardhaman",
    "Bishnupur, Paschim Bardhaman",
    "Panchmura, Paschim Bardhaman",
    "Ranishwar, Paschim Bardhaman",
    "Andal, Paschim Bardhaman",
    "Jitpur, Paschim Bardhaman",
    "Madhusree, Paschim Bardhaman",
    "Kenduli, Paschim Bardhaman",
    "Jalangi, Paschim Bardhaman",
    "Kolkata, Paschim Bardhaman",
    "Dumuria, Paschim Bardhaman",
    "Durgapur, Paschim Bardhaman",
    "Arambagh, Paschim Bardhaman",
    "Birbhum, Paschim Bardhaman",
    "Bankura, Paschim Bardhaman",
    "Raiganj, Paschim Bardhaman",
    "Hatsingimari, Paschim Bardhaman",
    "Kalimpong, Paschim Bardhaman",
    "Alampur, Paschim Bardhaman",
    "Mahammadpur, Paschim Bardhaman",
    "Sankrail, Paschim Bardhaman",
    "Saptarshi, Paschim Bardhaman",
    "Amraipur, Paschim Bardhaman",
    "Khadinapara, Paschim Bardhaman",
    "Shyampur, Paschim Bardhaman",
    "Khadinapara, Paschim Bardhaman",
    "Kharagpur, Paschim Medinipur",
    "Medinipur, Paschim Medinipur",
    "Contai, Paschim Medinipur",
    "Daspur, Paschim Medinipur",
    "Panskura, Paschim Medinipur",
    "Tamluk, Paschim Medinipur",
    "Debra, Paschim Medinipur",
    "Mahishadal, Paschim Medinipur",
    "Bhangore, Paschim Medinipur",
    "Nandigram, Paschim Medinipur",
    "Egra, Paschim Medinipur",
    "Mochida, Paschim Medinipur",
    "Patashpur, Paschim Medinipur",
    "Bhupatinagar, Paschim Medinipur",
    "Salboni, Paschim Medinipur",
    "Khejuri, Paschim Medinipur",
    "Shibpur, Paschim Medinipur",
    "Jhargram, Paschim Medinipur",
    "Bagnan, Paschim Medinipur",
    "Raghunathganj, Paschim Medinipur",
    "Chandrakona, Paschim Medinipur",
    "Gokulpur, Paschim Medinipur",
    "Shibpur, Paschim Medinipur",
    "Kashipur, Paschim Medinipur",
    "Pachcham, Paschim Medinipur",
    "Koyra, Paschim Medinipur",
    "Pingla, Paschim Medinipur",
    "Sankrail, Paschim Medinipur",
    "Bardhan, Paschim Medinipur",
    "Khatra, Paschim Medinipur",
    "Jangalmahal, Paschim Medinipur",
    "Bansberia, Paschim Medinipur",
    "Panchkura, Paschim Medinipur",
    "Chandannagar, Paschim Medinipur",
    "Ranishwar, Paschim Medinipur",
    "Raghunathganj, Paschim Medinipur",
    "Gora, Paschim Medinipur",
    "Paschim Manikpur, Paschim Medinipur",
    "Kalyanpur, Paschim Medinipur",
    "Kalapathar, Paschim Medinipur",
    "Dumjur, Paschim Medinipur",
    "Sankharipur, Paschim Medinipur",
    "Kumirdaha, Paschim Medinipur",
    "Singhi, Paschim Medinipur",
    "Hesab, Paschim Medinipur",
    "Kamath, Paschim Medinipur",
    "Sarenga, Paschim Medinipur",
    "Nischintapur, Paschim Medinipur",
    "Jumjar, Paschim Medinipur",
    "Bhagawanpur, Paschim Medinipur",
    "Parul, Paschim Medinipur",
    "Jagannathganj, Paschim Medinipur",
    "Nawabganj, Paschim Medinipur",
    "Maheshpur, Paschim Medinipur",
    "Madhabpur, Paschim Medinipur",
    "Bengaluru, Paschim Medinipur",
    "Narasimhapur, Paschim Medinipur",
    "Bhangram, Paschim Medinipur",
    "Amraipur, Paschim Medinipur",
    "Purandarpur, Paschim Medinipur",
    "Birbhum, Paschim Medinipur",
    "Gajole, Paschim Medinipur",
    "Tarsipur, Paschim Medinipur",
    "Shivpur, Paschim Medinipur",
    "Bhubaneshwar, Paschim Medinipur",
    "Kolkata, Paschim Medinipur",
    "Chandigarh, Paschim Medinipur",
    "Bosepara, Paschim Medinipur",
    "Bagdah, Paschim Medinipur",
    "Burdwan, Paschim Medinipur",
    "Halisahar, Paschim Medinipur",
    "Kanchrapara, Paschim Medinipur",
    "Raiganj, Paschim Medinipur",
    "Magra, Paschim Medinipur",
    "Burdwan, Purba Bardhaman",
    "Asansol, Purba Bardhaman",
    "Raniganj, Purba Bardhaman",
    "Durgapur, Purba Bardhaman",
    "Kulti, Purba Bardhaman",
    "Jamuria, Purba Bardhaman",
    "Barabani, Purba Bardhaman",
    "Bishnupur, Purba Bardhaman",
    "Panchmura, Purba Bardhaman",
    "Andal, Purba Bardhaman",
    "Kenduli, Purba Bardhaman",
    "Jalangi, Purba Bardhaman",
    "Brajmohanpur, Purba Bardhaman",
    "Arambagh, Purba Bardhaman",
    "Raghunathganj, Purba Bardhaman",
    "Madhusree, Purba Bardhaman",
    "Baranagar, Purba Bardhaman",
    "Fakirganj, Purba Bardhaman",
    "Gourangapur, Purba Bardhaman",
    "Uttarpara, Purba Bardhaman",
    "Shibpur, Purba Bardhaman",
    "Sitarampur, Purba Bardhaman",
    "Uchalan, Purba Bardhaman",
    "Banshberia, Purba Bardhaman",
    "Paschim Bardhaman, Purba Bardhaman",
    "Shahbazpur, Purba Bardhaman",
    "Nayabari, Purba Bardhaman",
    "Kolar, Purba Bardhaman",
    "Ramsagar, Purba Bardhaman",
    "Bagnan, Purba Bardhaman",
    "Udaypur, Purba Bardhaman",
    "Alampur, Purba Bardhaman",
    "Mahammadpur, Purba Bardhaman",
    "Narayanpur, Purba Bardhaman",
    "Ranishwar, Purba Bardhaman",
    "Balarampur, Purba Bardhaman",
    "Kolkata, Purba Bardhaman",
    "Gokulpur, Purba Bardhaman",
    "Nandigram, Purba Bardhaman",
    "Haroa, Purba Bardhaman",
    "Satyen Bagan, Purba Bardhaman",
    "Singra, Purba Bardhaman",
    "Sankrail, Purba Bardhaman",
    "Dumur, Purba Bardhaman",
    "Durgapur, Purba Bardhaman",
    "Shahbazpur, Purba Bardhaman",
    "Kamath, Purba Bardhaman",
    "Ushgram, Purba Bardhaman",
    "Garkal, Purba Bardhaman",
    "Bhagalpur, Purba Bardhaman",
    "Jagannathganj, Purba Bardhaman",
    "Bamunari, Purba Bardhaman",
    "Khatra, Purba Bardhaman",
    "Bankura, Purba Bardhaman",
    "Khagra, Purba Bardhaman",
    "Kashipur, Purba Bardhaman",
    "Brahmanpara, Purba Bardhaman",
    "Jasur, Purba Bardhaman",
    "Baranagar, Purba Bardhaman",
    "Raghunathganj, Purba Bardhaman",
    "Contai, Purba Medinipur",
    "Tamluk, Purba Medinipur",
    "Egra, Purba Medinipur",
    "Panskura, Purba Medinipur",
    "Nandigram, Purba Medinipur",
    "Mahishadal, Purba Medinipur",
    "Khejuri, Purba Medinipur",
    "Pingla, Purba Medinipur",
    "Tamluk, Purba Medinipur",
    "Panchmura, Purba Medinipur",
    "Gokulpur, Purba Medinipur",
    "Debra, Purba Medinipur",
    "Bhangore, Purba Medinipur",
    "Burdwan, Purba Medinipur",
    "Raghunathganj, Purba Medinipur",
    "Sankrail, Purba Medinipur",
    "Shivpur, Purba Medinipur",
    "Barbaria, Purba Medinipur",
    "Uchalan, Purba Medinipur",
    "Madhusree, Purba Medinipur",
    "Bhagwanpur, Purba Medinipur",
    "Dumjur, Purba Medinipur",
    "Kalyanpur, Purba Medinipur",
    "Brahmapur, Purba Medinipur",
    "Nandigram, Purba Medinipur",
    "Kalyanpur, Purba Medinipur",
    "Baguiati, Purba Medinipur",
    "Bhagawanpur, Purba Medinipur",
    "Sonarpur, Purba Medinipur",
    "Ranishwar, Purba Medinipur",
    "Keshabpur, Purba Medinipur",
    "Tarakpur, Purba Medinipur",
    "Bansberia, Purba Medinipur",
    "Fakirganj, Purba Medinipur",
    "Raghunathganj, Purba Medinipur",
    "Bamunari, Purba Medinipur",
    "Balarampur, Purba Medinipur",
    "Mogra, Purba Medinipur",
    "Alampur, Purba Medinipur",
    "Digha, Purba Medinipur",
    "Srinagar, Purba Medinipur",,
    "Purulia, Purulia",
    "Balarampur, Purulia",
    "Jhalda, Purulia",
    "Kenda, Purulia",
    "Hura, Purulia",
    "Madhukunda, Purulia",
    "Barabazar, Purulia",
    "Chandrapur, Purulia",
    "Manbazar, Purulia",
    "Beldih, Purulia",
    "Neturia, Purulia",
    "Bagmundi, Purulia",
    "Raghunathganj, Purulia",
    "Chhatna, Purulia",
    "Patamda, Purulia",
    "Arsha, Purulia",
    "Dhurwa, Purulia",
    "Jitpur, Purulia",
    "Barudi, Purulia",
    "Bhurkunda, Purulia",
    "Tata, Purulia",
    "Kuchai, Purulia",
    "Jamshedpur, Purulia",
    "Sarenga, Purulia",
    "Kasmar, Purulia",
    "Shibpur, Purulia",
    "Paharidi, Purulia",
    "Balarampur, Purulia",
    "Jaitgarh, Purulia",
    "Kuchai, Purulia",
    "Dholka, Purulia",
    "Nabaipur, Purulia",
    "Muradi, Purulia",
    "Kochang, Purulia",
    "Haldibari, Purulia",
    "Shantipur, Purulia",
    "Simlagarh, Purulia",
    "Ramchandrapur, Purulia",
    "Kumirdaha, Purulia",
    "Dhalbhumgarh, Purulia",
    "Patgaon, Purulia",
    "Mahuldiha, Purulia",
    "Chandil, Purulia",
    "Pachapathar, Purulia",
    "Dhubri, Purulia",
    "Jarmundi, Purulia",
    "Raghunathganj, Purulia",
    "Madhupur, Purulia",
    "Ghurmuria, Purulia",
    "Purbabhaga, Purulia",
    "Alambazar, South 24 Parganas",
    "Amtala, South 24 Parganas",
    "Anulia, South 24 Parganas",
    "Balarampur, South 24 Parganas",
    "Baruipur, South 24 Parganas",
    "Bhangore, South 24 Parganas",
    "Bishnupur, South 24 Parganas",
    "Canning, South 24 Parganas",
    "Diamond Harbour, South 24 Parganas",
    "Gosaba, South 24 Parganas",
    "Jaynagar, South 24 Parganas",
    "Jibantala, South 24 Parganas",
    "Kakdwip, South 24 Parganas",
    "Kultali, South 24 Parganas",
    "Magra, South 24 Parganas",
    "Maheshtala, South 24 Parganas",
    "Mogra, South 24 Parganas",
    "Nandakumar, South 24 Parganas",
    "Namkhana, South 24 Parganas",
    "Narendrapur, South 24 Parganas",
    "Patharpratima, South 24 Parganas",
    "Sagar, South 24 Parganas",
    "Sankarpur, South 24 Parganas",
    "Sonarpur, South 24 Parganas",
    "Sundarban, South 24 Parganas",
    "Taratala, South 24 Parganas",
    "Thakurpukur, South 24 Parganas",
    "Uttarayan, South 24 Parganas",
    "Diamond, South 24 Parganas",
    "Alambazar, South 24 Parganas",
    "Bhabanipur, South 24 Parganas",
    "Bishnupur, South 24 Parganas",
    "Chandipur, South 24 Parganas",
    "Kolkata, South 24 Parganas",
    "Chandrapur, South 24 Parganas",
    "Dakshin, South 24 Parganas",
    "Dakshin Shibpur, South 24 Parganas",
    "Goyla, South 24 Parganas",
    "Harindanga, South 24 Parganas",
    "Hasnabad, South 24 Parganas",
    "Jadavpur, South 24 Parganas",
    "Jhargram, South 24 Parganas",
    "Kaliaganj, South 24 Parganas",
    "Khulna, South 24 Parganas",
    "Kumirmari, South 24 Parganas",
    "Madhyamgram, South 24 Parganas",
    "Magra, South 24 Parganas",
    "Malda, South 24 Parganas",
    "Mograhat, South 24 Parganas",
    "Raghunathganj, South 24 Parganas",
    "Shyampur, South 24 Parganas",
    "Sankrail, South 24 Parganas",
    "Uttorayon, South 24 Parganas",
    "Bhatpara, South 24 Parganas",
    "Barasat, South 24 Parganas",
    "Bhangore, South 24 Parganas",
    "Kankinara, South 24 Parganas",
    "Maheshtala, South 24 Parganas",
    "Shibpur, South 24 Parganas",
    "Sundarban, South 24 Parganas",
    "Rajarhat, South 24 Parganas",
    "Taki, South 24 Parganas",
    "Nabapally, South 24 Parganas",
    "Kochi, South 24 Parganas",
    "Baruipur, South 24 Parganas",
    "Beltala, South 24 Parganas",
    "Rajarhat, South 24 Parganas",
    "Baganpara, South 24 Parganas",
    "Banipur, South 24 Parganas",
    "Madhyamgram, South 24 Parganas",
    "Kolkata, South 24 Parganas",
    "Chandannagar, South 24 Parganas",
    "Garia, South 24 Parganas",
    "Parganas, South 24 Parganas",
    "Patharpratima, South 24 Parganas",
    "Madhyamgram, South 24 Parganas",
    "Dakshinshibpur, South 24 Parganas",
    "Raiganj, Uttar Dinajpur",
    "Karandighi, Uttar Dinajpur",
    "Itahar, Uttar Dinajpur",
    "Chopra, Uttar Dinajpur",
    "Islampur, Uttar Dinajpur",
    "Goalpokhar, Uttar Dinajpur",
    "Hemtabad, Uttar Dinajpur",
    "Kaliyaganj, Uttar Dinajpur",
    "Ranishwar, Uttar Dinajpur",
    "Paharudi, Uttar Dinajpur",
    "Sankar, Uttar Dinajpur",
    "Maldanga, Uttar Dinajpur",
    "Murarai, Uttar Dinajpur",
    "Kaliyaganj, Uttar Dinajpur",
    "Baidyabati, Uttar Dinajpur",
    "Agarpara, Uttar Dinajpur",
    "Dalkhola, Uttar Dinajpur",
    "Raiganj, Uttar Dinajpur",
    "Saksher Bazar, Uttar Dinajpur",
    "Kamarpara, Uttar Dinajpur",
    "Jalpaiguri, Uttar Dinajpur",
    "Buniadpur, Uttar Dinajpur",
    "Baharampur, Uttar Dinajpur",
    "Pundibari, Uttar Dinajpur",
    "Moynaguri, Uttar Dinajpur",
    "Patgram, Uttar Dinajpur",
    "Mothabari, Uttar Dinajpur",
    "Lalgarh, Uttar Dinajpur",
    "Rangapara, Uttar Dinajpur",
    "Jalpaiguri, Uttar Dinajpur",
    "Dinhata, Uttar Dinajpur",
    "Rajgram, Uttar Dinajpur",
    "Silampur, Uttar Dinajpur",
    "Hindapara, Uttar Dinajpur",
    "Bishnupur, Uttar Dinajpur",
    "Bairagirhat, Uttar Dinajpur",
    "Patabari, Uttar Dinajpur",
    "Uttarpara, Uttar Dinajpur",
    "Srinagar, Uttar Dinajpur",
    "Purulia, Uttar Dinajpur",
    "Sujapur, Uttar Dinajpur",
    "Madhyagram, Uttar Dinajpur",
    "Narayanpur, Uttar Dinajpur",
    "Ramkrishnapur, Uttar Dinajpur",
    "Subarnapur, Uttar Dinajpur",
    "Gour, Uttar Dinajpur",
    "Shibpur, Uttar Dinajpur",
    "Mahadipur, Uttar Dinajpur",
    "Durba, Uttar Dinajpur",
    "Madhyagram, Uttar Dinajpur",
    "Mothabari, Uttar Dinajpur",
    "Pratappur, Uttar Dinajpur",
    "Gobindapur, Uttar Dinajpur",
    "Baganpara, Uttar Dinajpur",
    "Sarkarpara, Uttar Dinajpur",
    "Gharghora, Uttar Dinajpur",
    "Dakshin, Uttar Dinajpur",
    "Raiganj, Uttar Dinajpur",
    "Radhakantapur, Uttar Dinajpur",
    "Durgapur, Uttar Dinajpur",
    "Kharbari, Uttar Dinajpur",
    "Mochindrapur, Uttar Dinajpur",
    "Ramchandrapur, Uttar Dinajpur",
    "Nadia, Uttar Dinajpur",
    "Khagrabari, Uttar Dinajpur",
    "Hilibari, Uttar Dinajpur",
    "Paharudi, Uttar Dinajpur",
    "Sadar, Uttar Dinajpur"
  ]

  export default citys